name: Debug Release Events

on:
  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release draft: ${{ github.event.release.draft }}"
          echo "Release prerelease: ${{ github.event.release.prerelease }}"
          echo "Full event:"
          echo '${{ toJSON(github.event) }}' | jq .
